# -*- coding: utf-8 -*-
"""21K-3278.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TwS1GMAqTH0RuJ88ecZ6xziUayv4HX9P

Q1.
"""

x = int(input("Enter first number:"))
y = int(input("Enter second number:"))

if (x == y) or (x - y == 9) or (y - x == 9) or (x + y == 9):
  print("True")

"""Q2."""

num1 = int(input("Enter the first positive number:"))
num2 = int(input("Enter the second positive number:"))

# Taking copies of both number
a = num1
b = num2


if (num1 > 0) and (num2 > 0):
  while (num2 != 0):
    temp = num2
    num2 = num1 % num2
    num1 = temp
else:
  print("Error! must had entered a positive number")
    
GCD = num1
print("The GCD is:")
print(GCD)

LCM = int((a * b) / GCD)
print("The LCM is:")
print(LCM)

"""Q3."""

str1 = str(input("Enter the first string:"))
str2 = str(input("Enter the second string:"))

if str2 == ((str1)[::-1]):
  print("The strings are palendrome")
else:
  print("Not a palendrome")

"""Q4."""

binary = 0
i = 1
x = int(input("Enter the integer to convert:"))

while x != 0 :
    rem = int(x) % 2
    x = x / 2
    binary = binary + rem*i
    i = i*10

print(binary)

